typography_spectrum: 0.4746811520308256
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4152768759522587
  lightness: 0.41163514042273164
  saturation: 0.6425722392741591
  rhythmicContrast: 0.5217221139464527
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3917586812749505
analytics:
  google: null
  facebook: null
  twitter: null
name: HiJoeMartin
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Joseph Martin
description: Chicago entrepreneur and UX designer with a love for making things simple
purpose: []
